In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Documents\Data analytics\projects\my-data-project\SaaS project\Raw data\ravenstack_subscriptions.csv")

In [3]:
df_copy = df.copy()
df_copy.sample(20)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
602,S-4fdfa3,A-5a3eb9,2024-11-09,NaN,Enterprise,18,3582,42984,False,False,False,False,monthly,True
1899,S-c27df9,A-6f50ae,2024-04-05,NaN,Pro,19,0,0,True,False,False,False,monthly,True
453,S-60b7c7,A-02fac6,2024-05-02,NaN,Enterprise,23,4577,54924,False,False,False,False,annual,False
3547,S-c847dc,A-22f2df,2024-12-26,NaN,Pro,6,0,0,True,False,False,False,annual,False
1218,S-a3e1e3,A-05d3b3,2024-09-26,NaN,Enterprise,9,0,0,True,False,False,False,monthly,True
1756,S-76b06c,A-54d94a,2024-08-06,NaN,Pro,27,1323,15876,False,False,False,False,monthly,True
2410,S-a82473,A-fda07f,2024-09-12,NaN,Enterprise,16,3184,38208,False,False,False,False,annual,True
155,S-672f1b,A-eafc6e,2023-08-08,NaN,Pro,27,1323,15876,False,False,False,False,monthly,True
795,S-4bfa1d,A-ce550d,2024-12-21,2024-12-30,Pro,35,1715,20580,False,False,False,True,monthly,True
2017,S-9a7851,A-4c38bc,2024-12-27,2024-12-28,Pro,36,1764,21168,False,False,False,True,annual,True
2548,S-e7fe6f,A-35083d,2024-07-22,NaN,Pro,42,2058,24696,False,True,False,False,annual,True
246,S-f75ac4,A-faa28c,2024-02-17,NaN,Enterprise,48,0,0,True,False,False,False,annual,True
1306,S-813cdc,A-39b19f,2023-07-04,NaN,Pro,20,980,11760,False,False,False,False,annual,True
2340,S-b7d291,A-f6b2fb,2024-10-17,2024-12-17,Pro,23,1127,13524,False,False,False,True,annual,True
3364,S-51f213,A-4e960a,2024-11-24,NaN,Pro,12,588,7056,False,False,False,False,monthly,True
4884,S-30008c,A-cc98bc,2024-05-26,NaN,Pro,54,2646,31752,False,True,False,False,annual,True
3095,S-e8d48e,A-2edab2,2024-06-19,NaN,Enterprise,17,3383,40596,False,False,False,False,annual,True
3121,S-373490,A-756192,2024-09-28,NaN,Enterprise,19,0,0,True,False,False,False,monthly,True
344,S-ed32c7,A-37f969,2023-10-24,NaN,Pro,30,1470,17640,False,False,False,False,annual,False
4029,S-2bc860,A-98a59a,2023-11-10,NaN,Pro,56,2744,32928,False,True,False,False,monthly,False

In [4]:
df_copy.shape

(5000, 14)

In [5]:
df_copy.columns = df_copy.columns.str.replace('_', '').str.lower()
df_copy.columns

Index(['subscriptionid', 'accountid', 'startdate', 'enddate', 'plantier',
       'seats', 'mrramount', 'arramount', 'istrial', 'upgradeflag',
       'downgradeflag', 'churnflag', 'billingfrequency', 'autorenewflag'],
      dtype='object')

In [6]:
datatype_mapping = {
    "subscriptionid": "string",
    "accountid": "string",
    "startdate": "datetime64[ns]",
    "enddate": "datetime64[ns]",
    "plantier": "string",
    "seats": "int64",
    "mrramount": "float64",
    "arramount": "float64",
    "istrial": "bool",
    "upgradeflag": "bool",
    "downgradeflag": "bool",
    "churnflag": "bool",
    "billingfrequency": "string",
    "autorenewflag": "bool"
}
df_copy = df_copy.astype(datatype_mapping)
df_copy.dtypes

subscriptionid      string[python]
accountid           string[python]
startdate           datetime64[ns]
enddate             datetime64[ns]
plantier            string[python]
seats                        int64
mrramount                  float64
arramount                  float64
istrial                       bool
upgradeflag                   bool
downgradeflag                 bool
churnflag                     bool
billingfrequency    string[python]
autorenewflag                 bool
dtype: object

In [7]:
df_copy.duplicated().sum()

np.int64(0)

In [8]:
df_copy.isna().sum()

subscriptionid         0
accountid              0
startdate              0
enddate             4514
plantier               0
seats                  0
mrramount              0
arramount              0
istrial                0
upgradeflag            0
downgradeflag          0
churnflag              0
billingfrequency       0
autorenewflag          0
dtype: int64

In [9]:
df_copy['subscriptionid'] = df_copy['subscriptionid'].str.strip().str.lower().str.replace('-', '')
df_copy['accountid'] = df_copy['accountid'].str.strip().str.lower().str.replace('-', '')
df_copy['plantier'] = df_copy['plantier'].str.strip().str.lower()
df_copy['billingfrequency'] = df_copy['billingfrequency'].str.strip().str.lower()
df_copy.head()

,subscriptionid,accountid,startdate,enddate,plantier,seats,mrramount,arramount,istrial,upgradeflag,downgradeflag,churnflag,billingfrequency,autorenewflag
0,s8cec59,a3c1a3f,2023-12-23,2024-04-12,enterprise,14,2786.0,33432.0,False,False,False,True,monthly,True
1,s0f6f44,a9b9fe9,2024-06-11,NaT,pro,17,833.0,9996.0,False,False,False,False,monthly,True
2,s51c0d1,a659280,2024-11-25,NaT,enterprise,62,0.0,0.0,True,True,False,False,annual,False
3,sf81687,ae7a1e2,2024-11-23,2024-12-13,enterprise,5,995.0,11940.0,False,False,False,True,monthly,True
4,scff5a2,aba6516,2024-01-10,NaT,enterprise,27,5373.0,64476.0,False,False,False,False,monthly,True

In [10]:
none = ['nan', 'null', 'n/a', 'na', '', 'none', 'None', 'N/A', 'NULL', ' NAN', 'NaN', 'NONE', 'Nan']
df_copy = df_copy.replace(none, np.nan)
df_copy.isna().sum()

subscriptionid         0
accountid              0
startdate              0
enddate             4514
plantier               0
seats                  0
mrramount              0
arramount              0
istrial                0
upgradeflag            0
downgradeflag          0
churnflag              0
billingfrequency       0
autorenewflag          0
dtype: int64

In [11]:
df_copy.to_csv(r'C:\Documents\Data analytics\projects\my-data-project\SaaS project\Analysis\cleaned_csvs\subscriptions_cleaned.csv', index=False)